### ISSUE TITLE
Allow going to older versions

### ISSUE THREAD

**Issue by ghost** [hjk789/NXEnhanced#22]
When nextdns updates, the script breaks so I want to go to older versions.

**Comment by hjk789** [comment]
You mean older versions of NX Enhanced? It breaks because NextDNS developers change something in the site's code which the script was relying on, then the script needs to be updated with this change in mind. So using NXE's older versions wouldn't help in this case.

But what is not working for you? It's by reporting that I can know when something breaks. Also, make sure that you are using the most recent version of NX Enhanced which at the moment is 3.2.

**Comment by ghost** [comment]
Raw DNS logs are showing up, but I disabled it.
Can’t screenshot at this time because not using computer at the moment.
Oh, and they have a button that streams every time it logs.

**Comment by hjk789** [comment]
Yeah, these changes will come in the next update, except the real-time logs, which will take more time. I'm currently working on another project, but soon I'll get back to NXE.

**Comment by ghost** [comment]
Ok :)
