### ISSUE TITLE
IP from non device query greyed out

### ISSUE THREAD

**Issue by katchy3132** [hjk789/NXEnhanced#26]
I have ND configured so that many devices I use are named but I have my router configured using a linked IP since I cant run ND on that device. NXEnhaced seems to grey out the IP of those queries

As it appears using NXE:
![image](https://user-images.githubusercontent.com/3707138/110463393-8656e680-80da-11eb-9ef8-c3a03288aa7b.png)

Without NXE: ( I greyed out part of the IP myself ) 
![image](https://user-images.githubusercontent.com/3707138/110463447-97075c80-80da-11eb-82b4-08f3ed90e385.png)

**Comment by hjk789** [comment]
It's not showing the IP because it's not even implemented yet. Since [NXE 3.0](https://github.com/hjk789/NXEnhanced/commit/f400aa78753fc925a05f19facc997dbefc5a1ac6) the Logs page code was redone, and a few details were left to implement, the IP is one of them, but because the IPs are always disabled in my config, I ended up forgetting to implement it. :P   But it will come in the next update. Thanks for the feedback!

**Comment by hjk789** [comment]
The new version is now released. Can you update and test if it's still happening?

**Comment by katchy3132** [comment]
still happening . Im testing using the chrome Version 4.4.3 (The greasy fork version is 2  weeks old )

**Comment by hjk789** [comment]
Still happening? That's weird. Are you sure you are using 4.4.3? It's working fine here: 
![Sem título2](https://user-images.githubusercontent.com/53979731/110981568-363c8600-835f-11eb-9fc0-b067da502e27.png)

The Greasy Fork version is discontinued, so it won't receive more updates.

**Comment by katchy3132** [comment]
> Still happening? That's weird. Are you sure you are using 4.4.3? It's working fine here:

tried it again and it now seems to be working. thanks. maybe was a caching error...

> The Greasy Fork version is discontinued, so it won't receive more updates.

it was nice to have around so that I don't need to run another extension just for this... 
thanks anyway for the initiative
