### ISSUE TITLE
Sort Allow/Deny Lists By Parent Domain

### ISSUE THREAD

**Issue by quantumpacket** [hjk789/NXEnhanced#4]
Using the current sorting it will alpha sort it this way:

```
*.edge-chat.facebook.com
*.fna.fbcdn.net
*.fs.microsoft.com
*.gmail.com
*.go.microsoft.com
*.google.com
*.static.xx.fbcdn.net
*.wac.edgecastcdn.net
*.wpc.edgecastcdn.net
*.www.facebook.com
```

I'm not sure I see the benefit of sorting by subdomain. However, it would be useful to alpha sort the domains by their parent domain like so. This makes it easy to spot mistakes where you add a domain, which is already covered by another. In addition, right-aligning it will make it a lot easier to see the hierarchy.

```
   *.wac.edgecastcdn.net
   *.wpc.edgecastcdn.net
*.edge-chat.facebook.com
      *.www.facebook.com
         *.fna.fbcdn.net
   *.static.xx.fbcdn.net
             *.gmail.com
            *.google.com
      *.fs.microsoft.com
      *.go.microsoft.com
```

**Comment by hjk789** [comment]
Yeah, yesterday I was thinking about that too, sorting by subdomain isn't much useful, as the root domains get scattered all over the list, but when implementing I didn't thought of that. The best would be to: 

- [X] sort by root domain then by each level of subdomain
- [x] with an option to choose whether to also sort by TLDs.

About the right-aligning, I did some quick testings on the site but it seems the site's layout doesn't respond with simple text aligning, but probably because I'm doing it the wrong way.

It would be good that when allowing/denying domains ... 
- [x] add a check that notifies the user that the provided subdomain is already included in an upper domain.    

This would help preventing new mistakes.

**Comment by quantumpacket** [comment]
@hjk789 I added `justify-content: flex-end` to this `<div class="flex-grow-1 d-flex align-items-center" style="opacity: 1; justify-content: flex-end;">` to get the following output:

![dns](https://user-images.githubusercontent.com/8516784/89129424-4fc54780-d4cb-11ea-984f-bb23b4120b9f.png)

Note: this is with your script disabled. I'm not sure how and where you're adding the elements to that list item, but the order may need to be changed or the proper flex properties applied.

**Comment by hjk789** [comment]
I'm not used to flex, good to know it's that simple. Here's the appearance after the changes: 
![Screenshot_2020-08-02 Allowlist - My First Configuration - NextDNS](https://user-images.githubusercontent.com/53979731/89135608-13aed880-d505-11ea-873d-84ce6d61b7f3.png)

The space on the right side is occupied with the input box.

**Comment by quantumpacket** [comment]
@hjk789 I would add the description input box before the domain like in screenshot so it can fill up all available space. I'd also move the favicon to after the domain so they too are aligned. I'll fiddle around with the script when I have more time this week.

**Comment by quantumpacket** [comment]
I found something interesting that we may want to add as a sort method. Say you want to sort by domain owner. Like `google.com` and `gmail.com` they don't share the same parent domain, but they are owned by Google. From what I can tell the favicon is hashed and used as the filename. So both these domains use the same favicon. So if I sort by favicon filename it will group the favicons together so I can see related services belonging to Google. Just an idea for a rainy day.

**Comment by hjk789** [comment]
Your suggestion of sorting by favicon won't work, because the favicon's filename is the domain's hex, which is different for every domain, even if the appearance of the favicon or the image's bytes are the same, the file name is not. So the only way to achieve that would be by recognizing the favicon's pixels or comparing the hash of the file's bytes, which is clearly unfeasible for just a sorting option.
