### ISSUE TITLE
Add all TLDs not working properly

### ISSUE THREAD

**Issue by chirag127** [hjk789/NXEnhanced#41]
**Issue URL**:  https://my.nextdns.io/123456/security

Add all TLDs  not add all tdl in one go, I have to repeat the process many times. 
Actually I have decided that i will rather maintain a allowlist for my children. So, i found this as the only option to block all tlds but still some rare tlds will remain unblocked do you know any other method of blocking all domains.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/127753215-78226a50-a2f9-482e-8d40-43807c01a60c.png)

![image](https://user-images.githubusercontent.com/76880977/127753243-52d0e59c-6c1b-414c-ab0b-b40b86ae6d49.png)
![image](https://user-images.githubusercontent.com/76880977/127753256-73428704-ad72-4860-b0b0-ce7a50a09e1c.png)
![image](https://user-images.githubusercontent.com/76880977/127753259-df730a61-0d99-4aae-8fa3-02b74a676c4c.png)

</details><br/>

<details><summary>System configuration:</summary>
chrome extension
</details><br/>

**Comment by hjk789** [comment]
I just tested here and it's failing too. Most likely it's the same problem in #40. It seems that the NextDNS guys did some changes server-side. One of these changes seems to be that only some of the TLDs are added, the other requests are refused by the server, but for some reason the refused request is now treated as a successful one, making NXE think it finished adding the TLDs when it didn't. And another change is that the time to wait after repeated requests seems to be much bigger now, making it take up to 10 minutes to finish what used to take seconds. I'll investigate what can be done to decrease this time or prevent the requests getting refused.

**Comment by 0xRustlang** [comment]
> I just tested here and it's failing too. Most likely it's the same problem in #40. It seems that the NextDNS guys did some changes server-side. One of these changes seems to be that only some of the TLDs are added, the other requests are refused by the server, but for some reason the refused request is now treated as a successful one, making NXE think it finished adding the TLDs when it didn't. And another change is that the time to wait after repeated requests seems to be much bigger now, making it take up to 10 minutes to finish what used to take seconds. I'll investigate what can be done to decrease this time or prevent the requests getting refused.

I and probably many users won't have problem with waiting even 30 minutes but have a complete import that won't trigger any anti abuse algorithms that seems that nextdns devs are developing.

Because making a new config from scratch take far more time and health (eye).

But the only problem here is those annoying algorithms in browsers that warn if a js takes too much time to run.

I don't know if they just warn or also automatically stop it may be.

If it be just a warning, it is no problem, but if it be automatically stopping script, it will be annoying.

I hope it be former.

By the way,
Thank you very much for your hard work.

This is so much great.

That damn nextdns should work on this futures but they went quiet since service got out of beta phase. :/

**Comment by hjk789** [comment]
@rustforfuture

> I and probably many users won't have problem with waiting even 30 minutes but have a complete import 

I'm working on a workaround for this problem, I tried to find a way to make it take less time, but it seems there's no way to accomplish this, it always takes around 30 minutes to finish adding all TLDs. It's better than nothing though. I'll release it soon.

> that won't trigger any anti abuse algorithms that seems that nextdns devs are developing.

It's likely CloudFlare's DDOS protection system. Because the same device sends a barrage of requests in a short time, the server ends up thinking it's a possible attack and starts blocking the requests. Maybe the NextDNS devs made some tweaks in the protection settings.

> But the only problem here is those annoying algorithms in browsers that warn if a js takes too much time to run.

This only happens when a heavy processing is happening in JavaScript, heavy enough to lock up the whole tab. In NXE's case this doesn't happen.

> By the way,
> Thank you very much for your hard work.
> This is so much great.

Thanks! :)

> That damn nextdns should work on this futures but they went quiet since service got out of beta phase. :/

I have no idea what is the view of those guys for NextDNS. Maybe they want to add more features, but there's some obstacles preventing this, or they would like the idea of implementing them but they don't think it's worth it, or maybe it can be that they just don't care and think that what the site has now is enough.

**Comment by 0xRustlang** [comment]
Thank you very much.
Actually I said that time randomly and i don't care about how much time it takes (1 hour, 2 hour, etc) as long as all data restored (blacklist, whiltelist, etc)

The most great thing of this great project is automation of the work.

I previously (two years ago may be) didn't have eye issues and duplicated a profile manually and even though my eyes was somehow more healthy, my eyes get hurt alot.

And now that my eyes has issues, i can understand how much this project is by far great and helpful.

I always wish you the best, friend :)

I Wish you to always be healthy and happy.
Best regards.

**Comment by 0xRustlang** [comment]
Thank you very much for your great work.

I finally imported my backup and can use my nextdns account that i had removed its configs several months ago.

Really Thank you very much.
Best wishes.
