### ISSUE TITLE
Replace Allow/Deny Domain IFRAME With REST Request

### ISSUE THREAD

**Issue by quantumpacket** [hjk789/NXEnhanced#5]
I have not tested this yet, but has this been attempted?

Currently when you add a domain to the allow/deny lists using the buttons in the Logs tab it opens up an IFRAME, which does not always display correctly depending your screen zoom, font settings, addons that may alter layout, etc. This also requires the user to have to hit the spacebar to submit the domain.

An alternative is to emulate the action of adding a domain by submitting the same requests that would otherwise be sent from the allow/deny list tabs.

When you add a domain for the allow list it sends two requests to the server. The hex value is the domain hex-encoded. Adding `example.com` would do the following:

**Request 1**
```
Method: OPTIONS
URL: https://api.nextdns.io/configurations/YOUR_CONFIG/allowlist/hex:6578616d706c652e636f6d
```

**Request 2**
```
Method: PUT
URL: https://api.nextdns.io/configurations/YOUR_CONFIG/allowlist/hex:6578616d706c652e636f6d
JSON Payload: {"domain":"example.com","active":true}
```

The same could be done for the deny list. This would allow seamless integration that does not require an IFRAME and is a one click action. Thoughts?

**Comment by hjk789** [comment]
The first thing I tried before starting developing NX Enhanced was reproducing the HTTP request it makes when adding a domain. I tried resending the same request for a test domain. But because I sent only the OPTIONS request and not the PUT one, it didn't changed anything, so I thought it didn't work for some security reason in the server, and stopped trying. Now I tested using a hexed test domain, sending both requests, and it worked fine. This changes everything! I'm still learning about HTTP requests, I'm learning several new things with this project. 

This surely can be implemented. I just tested doing an HTTP request from `my.nextdns.io`, and it throws a CORS error. But when I created an iframe for `https://api.nextdns.io/configurations` and did the request from this iframe, it worked fine. So just need to change the script to create this iframe, change both top window and iframe `document.domain` to `nextdns.io` (so that the iframe's content can be accessed freely), and when clicking the allow/deny buttons, handover the hexed domain to the iframe, which will then send the HTTP requests. Much simpler and easier.

Function in the iframe:
```javascript
function addToAllowDenyList(list, hex)
{
    const requestURL = "https://api.nextdns.io/configurations/<CONFIG ID>/" + list + "/hex:" + hex

    let xmlHttp = new XMLHttpRequest()
    xmlHttp.open("PUT", requestURL, false)  // In my tests, only PUT is necessary
    xmlHttp.send()
}
```

Access from the top window: 
```javascript
document.querySelector("iframe").contentWindow.addToAllowDenyList("allowlist", "6162632e636f6d")
```

**Comment by quantumpacket** [comment]
Awesome, look forward to seeing all these new changes.

> I'm still learning about HTTP requests, I'm learning several new things with this project.

Hey, that's where it all starts! If you need any help let me know.

**Comment by quantumpacket** [comment]
@hjk789 You do not need the IFRAME. The reason you are getting a CORS error is likely because you are not setting the HTTP header `Origin: https://my.nextdns.io` in the request.

**Comment by hjk789** [comment]
Tried that, but the browser doesn't let to manually set the Origin header: "Attempt to set a forbidden header was denied: Origin" in Firefox or "Refused to set unsafe header "Origin"" in Chrome. I did dome searching and it seems that using an iframe with a spoofed `document.domain` is the only way to do cross-subdomain requests client-side. Couldn't find any other way.
