### ISSUE TITLE
Support Official NextDNS API

### ISSUE THREAD

**Issue by quantumpacket** [hjk789/NXEnhanced#56]
Docs: https://nextdns.github.io/api/ (BETA)

Just creating this issue as a placeholder. Not all functionality can be replaced with the API at the moment (log access for now?). However, if they add support for ruleset management that could greatly simplify the extension.

**Comment by hjk789** [comment]
Yeah, I'm aware of this new API, it includes some additional features not included in the standard API. The problem is: it requires an API key provided by NextDNS devs, and I'm not sure if it would be a good idea to put the API key on an extension that anyone can easily view the code. On a compiled code it wouldn't be much of a problem, but extensions are wide open. The only safe solution would be sending all API requests to a server owned by me, which would include the API key. But that's not a good idea either, as the users would have to trust a third-party server. Of course, I would upload the server code here (without the key), but still...

**Comment by quantumpacket** [comment]
The API key is per user. I have my API key displayed on my NextDNS account settings page. All you need to do is have a way for people to supply it to the extension. For example the popular extensions [Octotree](https://github.com/ovity/octotree) and [RefinedGithub](https://github.com/refined-github/refined-github) have a setting option where you can supply your GitHub token. 

I'm even wondering if there is a way to use the password manager to store the token, but honestly if my token is able to be accessed in my browser by someone or something, then I should probably not be using my browser to login to NextDNS to begin with.

**Comment by hjk789** [comment]
Oh, I didn't noticed that they added the key to the account page. Cool. I think the user don't even need to inform the key, as the API itself already responds with it.

![api](https://i.imgur.com/pFrMijy.png)

**Comment by hjk789** [comment]
Seriously, I think it won't take long for NX Enhanced to become obsolete.
