### ISSUE TITLE
import a blocklist from a url 

### ISSUE THREAD

**Issue by minanagehsalalma** [hjk789/NXEnhanced#74]
allow adding a custom blocklist url

**Comment by hjk789** [comment]
Thanks for the suggestion, but it's unlikely that this would be implemented, not because I don't want, but because NextDNS itself wasn't made to deal with huge custom lists added by the users. Instead, you can go [here](https://github.com/nextdns/blocklists/issues) and suggest the list you want to be added natively to NextDNS. So unless NextDNS improve on that matter, this feature won't be implemented.
